"""empty message

Revision ID: 614376f1b63f
Revises: adbce4216a37
Create Date: 2025-12-21 03:35:06.875898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '614376f1b63f'
down_revision: Union[str, Sequence[str], None] = 'adbce4216a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dbtodolistitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_daily', sa.Boolean(), nullable=False))
        batch_op.drop_column('repeat_dayly')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dbtodolistitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_dayly', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('repeat_daily')

    # ### end Alembic commands ###
