"""empty message

Revision ID: adbce4216a37
Revises: 
Create Date: 2025-12-21 03:00:16.524854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'adbce4216a37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbtodolistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=False),
    sa.Column('create_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('update_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repeat_dayly', sa.Boolean(), nullable=False),
    sa.Column('repeat_weekly', sa.Boolean(), nullable=False),
    sa.Column('repeat_monthly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtodolistitem')
    # ### end Alembic commands ###
