"""empty message

Revision ID: e73b642eec49
Revises: 
Create Date: 2025-12-29 18:31:41.158679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e73b642eec49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop legacy tables only if they exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "dbbookmarkcategorylistitem" in existing_tables:
        op.drop_table("dbbookmarkcategorylistitem")
    if "dbbookmarklistitem" in existing_tables:
        op.drop_table("dbbookmarklistitem")
    
    # Only add description column if table exists and column doesn't exist
    if "dbtodolistitem" in existing_tables:
        existing_columns = set(col["name"] for col in inspector.get_columns("dbtodolistitem"))
        if "description" not in existing_columns:
            with op.batch_alter_table("dbtodolistitem", schema=None) as batch_op:
                batch_op.add_column(
                    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
                )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dbtodolistitem", schema=None) as batch_op:
        batch_op.drop_column("description")

    op.create_table(
        "dbbookmarklistitem",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("bookmark_id", sa.INTEGER(), nullable=False),
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("url", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dbbookmarkcategorylistitem",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
